// Phase-field model of solute precipitation / dissolution
// Author: Zexuan Xu, Idaho National Laboratory
// Contact: Zexuan Xu (xuzexuan@gmail.com) or Hai Huang (hai.huang@inl.gov)

#include "RandomNoise.h"

template<>
InputParameters validParams<RandomNoise>()
{
  InputParameters params = validParams<Kernel>();
  params.addRequiredParam<Real>("amplitude_alpha", "noise fluctuation magnitude");

  return params;
}

RandomNoise::RandomNoise(const std::string & name, InputParameters parameters) :
    Kernel(name, parameters),
    _amplitude_alpha(getParam<Real>("amplitude_alpha"))
{
  setRandomResetFrequency(EXEC_RESIDUAL);
}


Real
RandomNoise::computeQpResidual()
{

// _random is a random number betweem -1 and 1, generated by MOOSE
  
  _random = getRandomReal() * 2 - 1;
  
  return _test[_i][_qp] * (1 - _u[_qp]) * (1- _u[_qp]) * (1 + _u[_qp])* (1 + _u[_qp]) * _amplitude_alpha * _random;
  
}

Real
RandomNoise::computeQpJacobian()
{

  _random = getRandomReal() * 2 - 1;
  
  return _test[_i][_qp] * ( 4 * _u[_qp] * _u[_qp] * _u[_qp] * _phi[_j][_qp] - 4 * _u[_qp] * _phi[_j][_qp]) * _amplitude_alpha * _random;

  


}
