// Phase-field model of solute precipitation / dissolution
// Author: Zexuan Xu, Idaho National Laboratory
// Contact: Zexuan Xu (xuzexuan@gmail.com) or Hai Huang (hai.huang@inl.gov)
     
#include "RandomNoiseConc.h"

template<>
InputParameters validParams<RandomNoiseConc>()
{
  InputParameters params = validParams<Kernel>();
  params.addRequiredCoupledVar("phase","The coupled phase field order parameter");
  params.addRequiredParam<Real>("amplitude_beta", "noise fluctuation magnitude");
  return params;
}

RandomNoiseConc::RandomNoiseConc(const std::string & name, InputParameters parameters) :
    Kernel(name, parameters),
    _pf(coupledValue("phase")),
    _amplitude_beta(getParam<Real>("amplitude_beta"))
{
  setRandomResetFrequency(EXEC_RESIDUAL);
}


Real
RandomNoiseConc::computeQpResidual()
{

// _random is the random number betweem -1 and 1, generated by MOOSE  
  _random = getRandomReal() * 2 - 1;
  
// The random noise term in concentration equation is also determined by phase field variable
  
  return _test[_i][_qp] * (1 - _pf[_qp]) * (1- _pf[_qp]) * (1 + _pf[_qp])* (1 + _pf[_qp]) * _amplitude_beta * _random;
  
}

Real
RandomNoiseConc::computeQpJacobian()
{
  return 0; 

}
